### ISSUE TITLE
debug 时自定义传入程序的参数

### ISSUE THREAD

**Issue by Sunnny-3n** [tboox/xmake-vscode#2]
xmake-vscode 似乎在 debug 时不能自定义参数，望可以加入自定义参数的选项

**Comment by waruqi** [comment]
好的，我后两天改进下。

**Comment by waruqi** [comment]
我加上了，你更新下插件试试，xmake.additionalDebuggerTargetArguments 参数，是个 string数组，`["xxx", "sxx"]`

并且我同时修复了下vscode插件上的bug，建议xmake也同时更新下（不是必须），win最新版：https://github.com/tboox/xmake/releases/download/v2.2.1/xmake-v2.2.2-dev.exe

mac/linux直接更新master版本就好。

**Comment by Sunnny-3n** [comment]
可不可以根据 Target 的不同自动选择参数

**Comment by waruqi** [comment]
这个版本你先这么凑活着用吧，分target 需要想想怎么弄比较好，需要花点时间。

**Comment by waruqi** [comment]
我改了下，你再试试，版本：1.1.5

```json
 "xmake.debuggingTargetsArguments": {
        "default": ["stream", "http://www.baidu.com", "/tmp/a"],
        "target2": ["xxxx", "3444", "aaaa"]
    }
```

**Comment by wangzhankun** [comment]
> 我改了下，你再试试，版本：1.1.5
> 
> ```json
>  "xmake.debuggingTargetsArguments": {
>         "default": ["stream", "http://www.baidu.com", "/tmp/a"],
>         "target2": ["xxxx", "3444", "aaaa"]
>     }
> ```

请问这个配置文件是要写道哪里呀？如果是运行不是debug也可以使用这个方法吗？

**Comment by wangzhankun** [comment]
我找到了，是写到工作区的`setting.json`，路径是`.vscode/setting.json`，如果不存在可以创建。如果运行和debug模式应该添加的参数应该是：
```json
{
    "xmake.debuggingTargetsArguments": {
        "default": [
            "stream",
            "http://www.baidu.com",
            "/tmp/a"
        ],
    },
    
    "xmake.runningTargetsArguments": {
        "default": [
            "stream",
            "http://www.baidu.com",
            "/tmp/a"
        ],
    }
}
```

**Comment by xiaomi2077** [comment]
是不是又改成`./vscode/settings.json`文件了？

**Comment by yinkaisheng** [comment]
是.vscode/settings.json

> 我找到了，是写到工作区的`setting.json`，路径是`.vscode/setting.json`，如果不存在可以创建。如果运行和debug模式应该添加的参数应该是：
> 
> ```json
> {
>     "xmake.debuggingTargetsArguments": {
>         "default": [
>             "stream",
>             "http://www.baidu.com",
>             "/tmp/a"
>         ],
>     },
>     
>     "xmake.runningTargetsArguments": {
>         "default": [
>             "stream",
>             "http://www.baidu.com",
>             "/tmp/a"
>         ],
>     }
> }
> ```

是.vscode/settings.json，不是.vscode/setting.json
