### ISSUE TITLE
visual code的xmake插件与第三方插件vim有冲突

### ISSUE THREAD

**Issue by lubocheng** [tboox/xmake-vscode#4]
如题, 同时安装2个插件后,vim插件无法移动光标,无法出字..

**Comment by waruqi** [comment]
应该可以了，你试试，虽然修复了，但是问题原因还是很莫名。。

**Comment by lubocheng** [comment]
厉害,有空再试试~~

**Comment by lubocheng** [comment]
并没有看到这个工程有提交记录,我的xmake插件应该也没有更新,但是打开工程试了下，好像ok了..怎么做到的..~~~~~~~~

**Comment by waruqi** [comment]
我提交在dev分支，还没merge到master，之前版本1.1.5 现在版本 1.1.6，vscode会自动帮你更新的
